#配置端口号
server:
  port: 8081

#jdbc数据源
spring:
  #  连接数据库的数据源
  datasource:
    username: root
    password: zxy197879
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
#    关闭缓存
  thymeleaf:
    cache: false
#文件上传的配置
  servlet:
    multipart:
      enabled: true
      #允许上传的单个文件大小
      max-file-size: 1GB
      #每次上传请求允许的文件总大小
      max-request-size: 6GB

#扫描mapper配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.nyist.model








